### ISSUE TITLE
Is it possible to consolidate clones, extraction & project-builds directories?

### ISSUE THREAD

**Issue by adriaanm** [typesafehub/dbuild#171]
Could `extraction` & `project-builds` actually be the same directory, so they can share the same git checkout? It seems this would reduce the number of git repos (and disk space used) by a factor of three, as you could then also drop `clones` and go to the actual git remote(s) directly (for the community build, one set of check outs is 2G). `git fetch` is pretty efficient.

```
jenkins@ip-172-31-4-164:target-0.9.1$ 
cat ./project-builds/lift-json-136dd59c65fe14f89b96e5b095efcda60d7660c1/.git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = /home/jenkins/workspace/scala-2.11.x-integrate-community-build/...
...target-0.9.1/clones/411637aa9263c5290932027ca66a4f9e4700da97
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master

jenkins@ip-172-31-4-164:target-0.9.1$ 
grep 411637aa9263c5290932027ca66a4f9e4700da97 
  ./extraction/18f58ea36720e88c2e79edce7efe5b626fc09a5e/projects/*/.git/config

./extraction/18f58ea36720e88c2e79edce7efe5b626fc09a5e/projects
  /c6ce1b0d89a6291982d53cbce500ac6515a9a07d/.git/config:	
url = /home/jenkins/workspace/scala-2.11.x-integrate-community-build/
  target-0.9.1/clones/411637aa9263c5290932027ca66a4f9e4700da97
```

`du` tells me there are three copies of the .git directory on our file system:

```
29M	target-0.9.1/extraction/18f58ea36720e88c2e79edce7efe5b626fc09a5e/projects/c6ce1b0d89a6291982d53cbce500ac6515a9a07d/.git
29M	target-0.9.1/clones/411637aa9263c5290932027ca66a4f9e4700da97
29M	target-0.9.1/project-builds/lift-json-136dd59c65fe14f89b96e5b095efcda60d7660c1/.git
```

**Comment by cunei** [comment]
``du`` doesn't tell you the whole story: the ``extraction`` and ``project-builds`` directories are created via a clone on the local file system. By default, git creates such clones using hard links, sharing the data packs, therefore the git data files really only exist once. It is the reason why the ``clones`` directory exists in the first place.

**Comment by adriaanm** [comment]
Weird. I did a diff between the git directories and it wasn't empty. Is that expected?

**Comment by adriaanm** [comment]
Ok, so I guess the objects directories are hard linked as per http://stackoverflow.com/questions/11331324/git-clone-how-to-clone-local-repo-by-hardlinks, but that still leaves us with all the other stuff and the checkout. Anyway, you can close this won't fix, but I would still be interested to know the rationale for the different directories when you get a chance.

**Comment by cunei** [comment]
Sure: The ``clones`` directory stores a local copy of all the remote repositories; this copy persists across all of dbuild's runs. Each time dbuild is invoked, the existing local clones are updated via a "fetch" from the remote, to bring them up-to-date. From this single copy, the work copies are derived (using hard links). During each run, two separate clones are made, once for extraction and once for building. The reason they are separate is that the configuration used for the two is different: during extraction a certain Scala version may be used, for example, while a different (just compiled) version of Scala is used to compile during the build stage. Both directories are kept around for debugging purposes: should anything go wrong, it is possible to inspect the current status. However, these work directories are eventually automatically cleaned up. If you are looking to save space, a good place to look is under the ``~/.dbuild`` directory. All of the artifacts generated by dbuild are cached in a custom-format repository maintained there, together with metadata concerning the build. There is currently no automatic cleanup: the directory just keeps growing indefinitely. It is ok to delete the cache directories in there every now and then (as long as no build is underway). Automatic cleanup of the cache is one of the pending items to be implemented for dbuild: I am adding further details in a comment to #170.
Note that there is a separate cache directory for each release of dbuild; it is therefore advisable to delete the previous caches whenever dbuild is upgraded, in order to save space.

**Comment by adriaanm** [comment]
Thanks!
